### ISSUE TITLE
Consulta de Limitacions en peticions amb multiples fitxers

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/enviafib#241]
Hem de saber si s'han d'aplicar limitacions quan tenim una petició de múltiples fitxers en els següents casos:

(1) Limit de mida cada  fitxer pujat.
(2) Limit en el numero de fitxers a pujar 
(3) Limit mida total de la suma de tots els fitxers a firmar.

S'ha de determinar si s'han de fer i un valor per defecte.
En principi del que s'hagi de fer aniria a propietats de enviafib.properties.

**Comment by ptrias-fundaciobit** [comment]
S'ha decidit que no tendrem en compte cap limitació perque ja la fa PortaFIB
