### ISSUE TITLE
Estil de menú més modern

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/enviafib#246]
Estil de menú més modern: canvi de tipus de lletra, més gran, més espaiat, potser una icona per cada entrada, ...

![imatge](https://user-images.githubusercontent.com/17084256/198574524-b388704e-eb7e-470d-97dc-d1dc6ddbeae9.png)

**Comment by ptrias-fundaciobit** [comment]
S'ha decidit en reunió que el menú d'administrador es pot deixar com està no fa falta modificar-ho
