### ISSUE TITLE
Demanar codi DIR3 del funcionari.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/enviafib#258]
Quan estigui actiu el plugin de DataBaseEstructuraOrganitzativa (es.caib.enviafib.showmenuestructuraorganitzativa=true) despres de configurar l'usuari quan entra per primera vegada, s'ha de revisar el DIR3. Si aquest no existeix llavors s'ha de demanar el codi DIR3 de la unitat on es troba el funcionari. Com a ajuda passar-li aquesta URL per a facilitar al funcionari la trobada del seu codi DIR3: https://intranet.caib.es/dir3caib/unidad/list

**Comment by ptrias-fundaciobit** [comment]
Resolt a issue #301
