### ISSUE TITLE
Fer que sempre es mostri el menú de les opcions de firma en la capçalera

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/enviafib#263]
Issue relacionat: "Moure les opcions de firma del menú d'Usuari a un boto desplegable d'adalt #245 "

Fer que sempre es mostri el menú de les opcions de firma en la capçalera, tant si es USER com ADMIN.
El problema està en saber quan esta seleccionada la pipella "USER" des de cap.jsp o des del CapPreparer.java

![imatge](https://user-images.githubusercontent.com/17084256/201605840-1fa0abaf-78b3-4ca1-92c2-1d193b4234c4.png)

**Comment by ptrias-fundaciobit** [comment]
Arreglat!
