### ISSUE TITLE
Apareix un error al obrir la informació de una petició de firma de tipus flux de firmes

### ISSUE THREAD

**Issue by fbosch-fundaciobit** [GovernIB/enviafib#265]
Apareix un missatge d'error a la pàgina de informació de una petició pendent a una petició de firma de flux:

![image](https://user-images.githubusercontent.com/40387703/202399558-f5ad2db9-2618-4760-89f1-1d61f921dec3.png)

S'ha de solucionar. Comprovar si l'error realment amaga alguna informació important o no, i solventrho o amagar el missatge.

**Comment by ptrias-fundaciobit** [comment]
En molts de mesos no s'ha torant a produir l'error. Quan torni a apareixer es crearà un nou issue
