### ISSUE TITLE
Revisar com s'informen les metadades mínimes obligatòries

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/enviafib#266]
S'ha de revisar com s'informen les metadades dels documents abans de guardar-ho a arxiu:

-     eni:origen: 1   Vol dir document generat per l'administració.
-     eni:tipo_doc_ENI: TDxx (definit automàticament a partir del desplegable de tipus de document). 
-     eni:estado_elaboracion: EE01    Correspon a document original
-     eni:cod_clasificacion: Codi de la sèrie  TDxx (definit automàticament a partir del desplegable de tipus de document). Vos adjunt la taula d'equivalències tipus eni-sèrie documental.
-     eni:nombre_formato: Format del document: DOC, PDF,... normalment seran PDF
-     eni:extension_formato: extensió del document (.pdf,.docx , ...).
-     eni:id_tramite: Entenem que mai s'informarà amb cap codi SIA perquè es tracta de documents que van a aquestes sèries artificials. Els documents que arriben per integració d'eines de tramitació sí el tindran i acabaran a una altra sèrie.

Relació tipua document NTI - sèrie documental:

TD01 Resolució - SD01333
TD02 Acords- SD01334
TD03 Contractes - SD01335
TD04 Convenis - SD01336
TD05 Declaracions - SD01337
TD06 Comunicacions - SD01338
TD07 Notificacioins - SD01339
TD08 Publicacions- SD01340
TD09 Justificants de recepció- SD01342
TD10 Actes - SD01342
TD11 Certificat  - SD01343
TD12 Diligència - SD01344
TD13 Informe - SD01345
TD14 Sol.licitud - SD01346
TD15 Denúncia - SD01347
TD16 Al.legació - SD01348
TD17 Recurs - SD01349
TD18 Comunicació al ciutadà - SD01350
TD19 Factura - SD01351
TD20 Altra documentació aportada - SD01352
TD99 Altres - SD01353

**Comment by ptrias-fundaciobit** [comment]
Comprovat que tot s'informa correctament. S'ha afegit al script d'updates les series documenals correctes.
