### ISSUE TITLE
Crear una ajuda-manual d'usuari a dins l'aplicació que es pugui informar dinàmicament.

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/enviafib#315]
Crear una secció d'ajuda on podrem posar el manual d'usuari de l'aplicació. Aquest manual, estarà format per un conjunt de pàgines html dinàmiques que conformaran l'ajuda a l'usuari, per exemple
    - Inici
    - Primer accés i configuració de l'usuari
    - Pantalla principal 
    - Enviar a signar un document
    - Enviar a signar un document a una persona externa
    - Configurar un flux de firma amb l'assistent
    - Remetre documents signats a un tercer

Un exemple que ha agradat molt la OAE és l'Ajuda que han fet a l'aplicació VALIB (https://intranet.caib.es/valibback/ajuda/recepcio/).

Es podria plantejar fer com una espècie de component d'ajuda reutilitzable per altres aplicacions nostres.

**Comment by ptrias-fundaciobit** [comment]
![image](https://github.com/GovernIB/enviafib/assets/95921330/f7bac89c-d6fe-4a2d-a802-70ba1dd637f5)
Així quedará l'estructura visual. Farem un altre issue per redactar les FAQs
