### ISSUE TITLE
Millores en la pantalla de Plugi d'estructura organitzativa

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/enviafib#324]
(1) Quan s'espitgi el boto de fer actiu un plugin la resta automaticament s'hauria de desactivar. Només un sol plugin pot estar actiu a la vegada. Ocultar el boto de "Prohibit"

(2) El boto de validar persona es confon amb el d'activar plugin. Canvia la icona per una cosa similar a la segona captura.

![imatge](https://github.com/GovernIB/enviafib/assets/17084256/d777c9b8-3001-40f3-bde7-0643b52974ae)

![imatge](https://github.com/GovernIB/enviafib/assets/17084256/73040708-ee20-488a-b952-2e541973807e)

**Comment by ptrias-fundaciobit** [comment]
Fet
