### ISSUE TITLE
Quan entres per primera vegada a l'aplicació no te detecta idioma

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/enviafib#339]
Quan entres per primera vegada a l'aplicació no detecta idioma de l'usuari i no surten els literals de la pantalla. Hauria de navegar per defecte en català.

Es molt probable que el problema sigui que està agafant els idiomes suportats i no suportats, i hauria de agafar nomes els suportats, i hauria d'agafar també el primer (ca)

![image](https://github.com/GovernIB/enviafib/assets/17315737/8c07e670-5ef6-4af8-9767-dfa4f4ec6d73)

**Comment by anadal-fundaciobit** [comment]
El cas en particular no s'ha pogut reproduir, fins i tot posant navegador angles i idioma per defecte anglès.
S'han realitzat les següents modificacions:
(1) Check de idiomes null i buits
(2) Check de idioma obtingut estigui suportat
(3) Filtrar idiomes select per mostrar només idiomes suportats.
