### ISSUE TITLE
Error de Mapping en el llistat de Peticions

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/enviafib#343]
Error de Mapping de valors  en el llistat de Peticions.

![imatge](https://github.com/GovernIB/enviafib/assets/17084256/373204e7-7a29-49aa-bef4-adb1315e9184)

**Comment by ptrias-fundaciobit** [comment]
Aquest error es produeix perque hi ha peticions antigues amb tipus documentals que no estan suportats. No es preocupant.
